export const FETCHING_MEETINGS = 'FETCHING_MEETINGS';
export const FETCH_MEETINGS_SUCCESS = 'FETCH_MEETINGS_SUCCESS';
export const FETCH_MEETINGS_FAILED = 'FETCH_MEETINGS_FAILED';

export const FETCHING_EMPLOYEES = 'FETCHING_EMPLOYEES';
export const FETCH_EMPLOYEES_SUCCESS = 'FETCH_EMPLOYEES_SUCCESS';
export const FETCH_EMPLOYEES_FAILED = 'FETCH_EMPLOYEES_FAILED';

export const CREATING_ENDORSEMENT = 'CREATING_ENDORSEMENT';
export const CREATE_ENDORSEMENT_SUCCESS = 'CREATE_ENDORSEMENT_SUCCESS';
export const CREATE_ENDORSEMENT_FAILED = 'CREATE_ENDORSEMENT_FAILED';

export const UPDATING_ENDORSEMENT = 'UPDATING_ENDORSEMENT';
export const UPDATE_ENDORSEMENT_SUCCESS = 'UPDATE_ENDORSEMENT_SUCCESS';
export const UPDATE_ENDORSEMENT_FAILED = 'UPDATE_ENDORSEMENT_FAILED';

export const CREATING_MEETING = 'CREATING_MEETING';
export const CREATE_MEETING_SUCCESS = 'CREATE_MEETING_SUCCESS';
export const CREATE_MEETING_FAILED = 'CREATE_MEETING_FAILED';

export const ADDING_ATTENDEE = 'ADDING_ATTENDEE';
export const ADD_ATTENDEE_SUCCESS = 'ADD_ATTENDEE_SUCCESS';
export const ADD_ATTENDEE_FAILED = 'ADD_ATTENDEE_FAILED';

export const DELETING_MEETING = 'DELETING_MEETING';
export const DELETE_MEETING_SUCCESS = 'DELETE_MEETING_SUCCESS';
export const DELETE_MEETING_FAILED = 'DELETE_MEETING_FAILED';

export const UPDATING_MEETING = 'UPDATING_MEETING';
export const UPDATE_MEETING_SUCCESS = 'UPDATE_MEETING_SUCCESS';
export const UPDATE_MEETING_FAILED = 'UPDATE_MEETING_FAILED';